name: chexnet-medical-ai

channels:
  - nvidia
  - pytorch
  - defaults

dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - scikit-learn
  - pillow
  - pandas
  - pytorch==2.3.0
  - torchvision==0.18.0
  - pytorch-cuda=11.8
